export const dashboardStats = [
  {
    label: "Total Leads",
    value: "1,248",
    trend: "+12.4%",
    previousLabel: "vs last month",
    previousValue: "1,110",
    cardClass: "from-[#EEF2FC] to-[#f5f8ff]",
  },
  {
    label: "Qualified Leads",
    value: "326",
    trend: "+8.1%",
    previousLabel: "vs last month",
    previousValue: "301",
    cardClass: "from-[#ecfdf9] to-[#f2fcfa]",
  },
  {
    label: "Conversion Rate",
    value: "26.1%",
    trend: "+2.8%",
    previousLabel: "vs last month",
    previousValue: "25.4%",
    cardClass: "from-[#eef0f8] to-[#f6f7fc]",
  },
  {
    label: "Revenue",
    value: "$82,400",
    trend: "+14.2%",
    previousLabel: "vs last month",
    previousValue: "$72,150",
    cardClass: "from-[#ecfdf5] to-[#f3fdf8]",
  },
];

export const merchantStats = [
  {
    label: "Total Active Merchants",
    value: "102",
    trend: "+8.1%",
    previousLabel: "vs last month",
    previousValue: "301",
    cardClass: "from-[#ecfdf9] to-[#f2fcfa]",
  },
  {
    label: "Total Inactive Merchants",
    value: "102",
    trend: "+4.5%",
    previousLabel: "vs last month",
    previousValue: "98",
    cardClass: "from-[#ecfdf5] to-[#f3fdf8]",
  },
  {
    label: "Total Merchants",
    value: "204",
    trend: "+12.4%",
    previousLabel: "vs last month",
    previousValue: "180",
    cardClass: "from-[#EEF2FC] to-[#f5f8ff]",
  },
  {
    label: "Total Payment Gateway Merchants",
    value: "102",
    trend: "+4.5%",
    previousLabel: "vs last month",
    previousValue: "98",
    cardClass: "from-[#EEF2FC] to-[#f5f8ff]",
  },
];  
export const merchants = [
  {
    id: "LD-101",
    name: "Aarav Sharma",
    company: "Nimbus Labs",
    email: "aarav@nimbuslabs.com",
    phone: "+91 98765 43210",
    status: "Qualified",
    source: "Website",
    score: 88,
    priority: "Warm",
    assignee: "Priya Nair",
    assigneeInitials: "PN",
    assigneeColor: "#2D4CC8",
    category: "Online PG",
    workType: "Merchant",
  },
  {
    id: "LD-102",
    name: "Meera Kapoor",
    company: "Blue Orbit",
    email: "meera@blueorbit.ai",
    phone: "+91 98112 33445",
    status: "Proposal",
    source: "Referral",
    score: 92,
    priority: "Hot",
    assignee: "Rahul Mehta",
    assigneeInitials: "RM",
    assigneeColor: "#25a36f",
    category: "POS & QR",
    workType: "Reseller",
  },
  {
    id: "LD-103",
    name: "Rohan Verma",
    company: "CraftStack",
    email: "rohan@craftstack.io",
    phone: "+91 99887 76655",
    status: "New",
    source: "Campaign",
    score: 67,
    priority: "Cold",
    assignee: "Unassigned",
    assigneeInitials: "—",
    assigneeColor: "#94a3b8",
    category: "Payment Gateway",
    workType: "Payment Gateway",
  },
  {
    id: "LD-104",
    name: "Siya Menon",
    company: "FlowPulse",
    email: "siya@flowpulse.com",
    phone: "+91 91234 56789",
    status: "Won",
    source: "LinkedIn",
    score: 95,
    priority: "Hot",
    assignee: "Anita Desai",
    assigneeInitials: "AD",
    assigneeColor: "#40C3CF",
    category: "Ecommerce / D2C",
    workType: "Merchant",
  },
  {
    id: "LD-105",
    name: "Kabir Singh",
    company: "NovaSphere",
    email: "kabir@novasphere.co",
    phone: "+91 90909 81818",
    status: "Qualified",
    source: "Website",
    score: 84,
    priority: "Warm",
    assignee: "Vikram Joshi",
    assigneeInitials: "VJ",
    assigneeColor: "#13203F",
    category: "B2B Manufacturing",
    workType: "Merchant",
  },
  {
    id: "LD-106",
    name: "Diya Iyer",
    company: "PaySwift",
    email: "diya@payswift.in",
    phone: "+91 98700 11223",
    status: "New",
    source: "Talk to Expert",
    score: 71,
    priority: "Cold",
    assignee: "Unassigned",
    assigneeInitials: "—",
    assigneeColor: "#94a3b8",
    category: "Reseller",
    workType: "Reseller",
  },
  {
    id: "LD-107",
    name: "Arjun Patel",
    company: "StackMint",
    email: "arjun@stackmint.com",
    phone: "+91 98222 44556",
    status: "Proposal",
    source: "Referral",
    score: 89,
    priority: "Warm",
    assignee: "Priya Nair",
    assigneeInitials: "PN",
    assigneeColor: "#2D4CC8",
    category: "SaaS / Subscription",
    workType: "Payment Gateway",
  },
  {
    id: "LD-108",
    name: "Neha Gupta",
    company: "OrbitPay",
    email: "neha@orbitpay.io",
    phone: "+91 97654 32109",
    status: "Qualified",
    source: "Website",
    score: 93,
    priority: "Hot",
    assignee: "Rahul Mehta",
    assigneeInitials: "RM",
    assigneeColor: "#25a36f",
    category: "Travel / Bill Pay",
    workType: "Merchant",
  },
];

export const leads = [
  {
    id: "LD-201",
    name: "Rohan Verma",
    company: "CraftStack",
    email: "rohan@craftstack.io",
    phone: "+91 99887 76655",
    status: "New",
    source: "Website",
    score: 67,
    priority: "Cold",
    assignee: "Unassigned",
    assigneeInitials: "—",
    assigneeColor: "#94a3b8",
    category: "Ecommerce / D2C",
    workType: "Merchant",
  },
  {
    id: "LD-202",
    name: "Diya Iyer",
    company: "PaySwift",
    email: "diya@payswift.in",
    phone: "+91 98700 11223",
    status: "New",
    source: "Talk to Expert",
    score: 71,
    priority: "Cold",
    assignee: "Unassigned",
    assigneeInitials: "—",
    assigneeColor: "#94a3b8",
    category: "Reseller",
    workType: "Reseller",
  },
  {
    id: "LD-203",
    name: "Karan Malhotra",
    company: "QuickSettle",
    email: "karan@quicksettle.in",
    phone: "+91 98190 22334",
    status: "New",
    source: "Campaign",
    score: 74,
    priority: "Warm",
    assignee: "Priya Nair",
    assigneeInitials: "PN",
    assigneeColor: "#2D4CC8",
    category: "Payment Gateway",
    workType: "Payment Gateway",
  },
  {
    id: "LD-204",
    name: "Ananya Reddy",
    company: "ShopNest",
    email: "ananya@shopnest.com",
    phone: "+91 99001 44556",
    status: "New",
    source: "Referral",
    score: 82,
    priority: "Warm",
    assignee: "Unassigned",
    assigneeInitials: "—",
    assigneeColor: "#94a3b8",
    category: "Online PG",
    workType: "Merchant",
  },
  {
    id: "LD-205",
    name: "Vivek Nanda",
    company: "PartnerGrid",
    email: "vivek@partnergrid.io",
    phone: "+91 97650 88990",
    status: "New",
    source: "LinkedIn",
    score: 69,
    priority: "Cold",
    assignee: "Rahul Mehta",
    assigneeInitials: "RM",
    assigneeColor: "#25a36f",
    category: "B2B Manufacturing",
    workType: "Reseller",
  },
  {
    id: "LD-206",
    name: "Pooja Deshmukh",
    company: "FinBridge PG",
    email: "pooja@finbridgepg.com",
    phone: "+91 98230 66771",
    status: "New",
    source: "Website",
    score: 77,
    priority: "Warm",
    assignee: "Unassigned",
    assigneeInitials: "—",
    assigneeColor: "#94a3b8",
    category: "SaaS / Subscription",
    workType: "Payment Gateway",
  },
];

export const websiteFeatures = [
  {
    title: "Smart Lead Tracking",
    description: "Track every lead stage with clean visual pipelines and filters.",
  },
  {
    title: "Actionable Insights",
    description: "Monitor stats and trends to make faster growth decisions.",
  },
  
 
];

export const heroFormStepOneFields = [
  {
    id: "hero-industry",
    name: "industry",
    label: "Industry",
    placeholder: "Select industry",
    options: [
      { value: "ecommerce-d2c", label: "Ecommerce / D2C" },
      { value: "b2b-manufacturing", label: "B2B / Manufacturing Businesses" },
      { value: "saas-subscription-platforms", label: "SaaS / Subscription Platforms" },
      { value: "education-healthcare", label: "Education / Healthcare Services" },
      { value: "travel-bill-payments", label: "Travel / Bill Payments" },
      { value: "other-businesses", label: "Freelancers  / Other Businesses" },
    ],
  },
  
  
  


];

export const pricingPlans = [
  {
    name: "Starter",
    price: "$29/mo",
    description: "For growing teams launching their first CRM setup.",
    features: ["Up to 3 users", "Lead tracking", "Email support"],
  },
  {
    name: "Growth",
    price: "$79/mo",
    description: "For scaling teams that need automation and reporting.",
    features: ["Up to 10 users", "Advanced reports", "Priority support"],
  },
  {
    name: "Enterprise",
    price: "Custom",
    description: "For large organizations with custom workflows and controls.",
    features: ["Unlimited users", "SSO & roles", "Dedicated success manager"],
  },
];
